### ISSUE TITLE
Encoding of variable length fields in structs.

### ISSUE THREAD

**Issue by egillh210** [unstoppablejs/unstoppablejs#10]
See:

https://stackblitz.com/edit/typescript-nypqgy?file=index.ts

**Comment by josepot** [comment]
:thinking: I'm pretty sure that there is nothing wrong with the encoding of dynamic fields on tuples/structs.

There are [different kinds of tests](https://github.com/unstoppablejs/unstoppablejs/blob/bc0d80c8c1c75567111ce09bc8fde2bf23b0bb70/packages/solidity-codecs/src/tests/Tuple.test.ts#L14-L96) that ensure that this is working correctly, [according to the specs](https://docs.soliditylang.org/en/develop/abi-spec.html#use-of-dynamic-types). I know that b/c this wasn't always the case and I had to make a [couple](https://github.com/unstoppablejs/unstoppablejs/commit/4517f034959056e7f83836894f608bd419af94f9) of [fixes](https://github.com/unstoppablejs/unstoppablejs/commit/9cf15988dce01cae1b9a9a72ca4a5e581e7aa963) in the past :sweat_smile: .

But then: what's the deal with the stackblitz example? Well, those 2 snippets of code are not equivalent. [These are](https://stackblitz.com/edit/typescript-z5drqr?file=index.ts).

Can you notice that on the `AbiCoder.prototype.encode` function of ethers, the second argument must always be an Array? That's because that function implicitly wraps everything on a `tuple`. Why would they choose to do that is beyond me, but the thing is that what it's being actually encoded/decoded is in fact: `tuple(tuple(address base, address quote, uint openQuantity, address spender, address dex, bytes swapBytes))`.

Perhaps there is a bug in the `solidity-bindings` package, b/c there is some magic that it's done in there in order to encode/decode parameters on function arguments, so that the user doesn't have to define explicit tuples on every function... So, I'm not saying that there isn't a bug related to dynamic fields. I'm just saying that this is not a bug on the encoders.
