### ISSUE TITLE
[scale-ts] tracing for decoders

### ISSUE THREAD

**Issue by ryanleecode** [unstoppablejs/unstoppablejs#20]
unless i'm mistaken, i don't think there is a way to trace the path a decoder took when deserializing a scale binary. I'd suggest adding a decorator-like pattern for a decoder that lets you "trace the path it took" while also not sacrificing performance because its a decorator.

**Comment by josepot** [comment]
> unless i'm mistaken, i don't think there is a way to trace the path a decoder took when deserializing a scale binary.

This is something that can be accomplished via composition. So, if you need tracing, then you could "easily" create traceable codecs using the codecs of this library.

> I'd suggest adding a decorator-like pattern for a decoder that lets you "trace the path it took" while also not sacrificing performance because its a decorator.

I don't understand how decorators are relevant to this library... Please keep in mind that this library doesn't expose any classes, it only exposes functions.

**Comment by josepot** [comment]
Just to provide a "quick and dirty" example of how that could be possible, consider this code:

```ts
import { StringRecord, Codec, Struct as _Struct, createCodec } from "scale-ts"
import { mapStringRecord } from './utils'

class TraceableCodecError extends Error {
  codecTrace: string
  constructor(previous: Error, trace: string) {
    super(previous.name)
    this.cause = previous.cause
    this.stack = previous.stack
    this.codecTrace =
      previous instanceof TraceableCodecError
        ? trace + "." + previous.codecTrace
        : trace
  }
}

export const traceableFunction =
  <A extends Array<any>, T>(
    fn: (...args: A) => T,
    trace: string,
  ): ((...args: A) => T) =>
  (...args) => {
    try {
      return fn(...args)
    } catch (e) {
      if (e instanceof Error) {
        throw new TraceableCodecError(e, trace)
      } else {
        throw new TraceableCodecError(new Error(`uknown error ${e}`), trace)
      }
    }
  }

const traceableStructure = <Inner extends (...args: any[]) => any>(
  fns: StringRecord<Inner>,
): StringRecord<Inner> =>
  mapStringRecord(
    fns,
    (fn, key) => traceableFunction(fn, key as string),
  )

const StructEnc: typeof _Struct.enc = (encoders) =>
  _Struct.enc(traceableStructure(encoders))

const StructDec: typeof _Struct.dec = (decoders) =>
  _Struct.dec(traceableStructure(decoders))

export const Struct: typeof _Struct = <A extends StringRecord<Codec<any>>>(
  codecs: A,
) =>
  createCodec(
    StructEnc(
      mapStringRecord(codecs, (x) => x[0]) as StringRecord<A[keyof A][0]>,
    ),
    StructDec(
      mapStringRecord(codecs, (x) => x[1]) as StringRecord<A[keyof A][1]>,
    ),
  )

Struct.enc = StructEnc
Struct.dec = StructDec
```

This code creates a `Struct` codec creator with the same public API as the one in `scale-ts`, which has some traceability baked in. So, we could do the same with all the other codec-creators of `scale-ts` (`Tuple`, `Enum`, `Vector`, `Option`, etc) and then export that into a library like `@scale-ts/traces` and then make the development build use that library instead of `scale-ts`... That's just one example, of something that could be done on top of the current primitives... And please believe me: if it wasn't for the fact that I currently have bigger fish to fry, I would be building these kinds of things 🙂.

All I"m saying is that it's 100% possible to have really good traceability without baking it into the core primitives.
