### ISSUE TITLE
question: can I export scale file from MyCodec?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [unstoppablejs/unstoppablejs#26]
I did MyCodec in TS. Can I export scale file?

I would like to use Rust to generate rust parser for data (https://github.com/paritytech/subxt reads scale files and generates decoder).

**Comment by josepot** [comment]
I don't understand the question, sorry. Could you please explain a bit better what's that you are after?

**Comment by dzmitry-lahoda** [comment]
I declared SCALE codec in Typescript. How I can use same codec in Rust?

**Comment by josepot** [comment]
> I declared SCALE codec in Typescript. How I can use same codec in Rust?

This is clearly an x/y problem. There is not a standarized way of declaring SCALE codecs, and there is also not a standarized way of decoding SCALE data. Each library does it in the way that's most convenient for their use cases.

The way that PJS ecodes/decodes SCALE variants has nothing to do on how scale-ts encodes/decodes them... So, as you can imagine, without a standarized way of defining SCALE codecs, and without a standarized way of encoding/decoding complex codecs, it's completely impossible to have a common lingua for creating scale codecs.

So, how can you create the same codec in Rust? You can't (unless you create these standards and then create libraries that adhere to these standards, ofc).

The closest thing that we have to a common lingua is the FRAME Metadata definitions. So, perhaps you could create a FRAME metadata definition and then use the PAPI libraries that create SCALE codecs based on the metadata.

However, as I already mentioned before, I'm 99% sure that this is an x/y problem. So, perhaps it could help you to state the actual context and the actual problem that you are trying to solve.

Closing this for now, because this question clearly does not belong into this repo. However, feel free to keep the conversation in here.

**Comment by dzmitry-lahoda** [comment]
I have Typescript server which provides SCALE encoded data via websocket.

I want to call that server from Rust and parse data into something reasonable.

My current approach is to read scale-ts definition in that server and manually sync Rust to decode.

Just wanted to know if there is automated way to sync Rust decoder with Typescript encoder.
